#!/bin/bash

pwd

arduino-cli compile -b esp8266:esp8266:generic \
--output-dir /Users/alexkennedy/Developer/home/build \
--build-property "build.extra_flags=-DESP8266 -DSPEC=\"bulb4\" -DF_CRYSTAL=40000000" \
--library /Users/alexkennedy/Developer/home/lib \
/Users/alexkennedy/Developer/home/home.ino

python /Users/alexkennedy/Developer/home/espota.py -i 10.0.0.156 -f /Users/alexkennedy/Developer/home/build/home.ino.bin

arduino-cli compile -b esp8266:esp8266:generic \
--output-dir /Users/alexkennedy/Developer/home/build \
--build-property "build.extra_flags=-DESP8266 -DSPEC=\"bulb5\" -DF_CRYSTAL=40000000" \
--library /Users/alexkennedy/Developer/home/lib \
/Users/alexkennedy/Developer/home/home.ino

python /Users/alexkennedy/Developer/home/espota.py -i 10.0.0.52 -f /Users/alexkennedy/Developer/home/build/home.ino.bin
