version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/raspberrypi3-homeassistant:stable"
    volumes:
      - ./volumes/ha/config:/config
      - ./volumes/etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
  mosquitto:
    image: eclipse-mosquitto:2.0.11
    restart: unless-stopped
    volumes:
      - ./volumes/mqtt/config:/mosquitto/config
      - ./volumes/mqtt/data:/mosquitto/data
      - ./volumes/mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
