version: '3.3'

services:
  deploy:
    build: .
    volumes:
      - .:/deploy/scripts
      - ../lib:/deploy/lib
      - ../home.ino:/deploy/home/home.ino
      - ../build:/deploy/build
    command: sleep 1200
    privileged: true
    network_mode: host
